import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Navbar, NextUIProvider } from "@nextui-org/react";
import { Topbar } from "./_shared/_components/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark text-foreground bg-background">
      <body className={inter.className}>
        <StoreProvider>
          <NextUIProvider>{children}</NextUIProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
