import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Navbar, NextUIProvider } from "@nextui-org/react";
import { Topbar } from "./_shared/_components/Topbar";
import { cookies } from "next/headers";
import { dashboardServices } from "./_dashboard/_services/dashboard.services";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  welcome,
}: Readonly<{
  children: React.ReactNode;
  welcome: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const accessToken = cookieStore.get("access_token")?.value;

  let userProfile: UserProfile | null = null;
  if (accessToken) {
    userProfile = await dashboardServices.fetchUserProfile(accessToken);
  }

  return (
    <html lang="en" className="dark text-text bg-background">
      <body className={inter.className}>
        <StoreProvider>
          <NextUIProvider>
            {accessToken ? (
              <>
                <Topbar />
                {children}
              </>
            ) : (
              welcome
            )}
          </NextUIProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
