import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Navbar, NextUIProvider } from "@nextui-org/react";
import { Topbar } from "./_shared/_components/Topbar";
import { cookies } from "next/headers";
import { dashboardServices } from "./_dashboard/_services/dashboard.services";
import { Sidebar } from "./_shared/_components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  welcome,
}: Readonly<{
  children: React.ReactNode;
  welcome: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const accessToken = cookieStore.get("access_token")?.value;

  return (
    <html lang="en" className="dark text-text bg-background">
      <body className={inter.className}>
        <StoreProvider>
          <NextUIProvider>
            {accessToken ? (
              <div className="flex">
                <Sidebar />
                <div className="w-full">
                  <Topbar />
                  {children}
                </div>
              </div>
            ) : (
              welcome
            )}
          </NextUIProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
